### ISSUE TITLE
Proxy config for module ciscospark - Usage in node	

### ISSUE THREAD

**Issue by aarcher11** [webex/spark-js-sdk#415]
Do you know the way to setup a https proxy within CiscoSpark module node.js environment?
I am actually using the module Ciscospark : 
var spark = require('ciscospark') 
then spark.rooms.create(..... When I execute "node MyProgram.js" I see that it cannot reach the remote @IP 192.237.193.202:443.

But how can I tell ciscospark module to send request along a proxy? Is there any environment variable for such purpose ?

**Comment by carlowahlstedt** [comment]
I'll second this question.

**Comment by jd-carroll** [comment]
@ianwremmel Is there any documentation on how to set a proxy for the spark sdk?  All of the spark API calls need to go through one of our corporate proxies, and I am struggling to identify where we would set that in the API.

**Comment by ianwremmel** [comment]
I'm afraid not. Most of the pieces are in place for proxy config, but nothing is exposed (even in a hacky way) that would let you use your own config. It's a design oversight that hasn't gotten the attention it deserves. Basically [`@ciscospark/http-core`](https://github.com/ciscospark/spark-js-sdk/tree/master/packages/node_modules/%40ciscospark/http-core) exports a customizable http client and [`@ciscospark/spark-core`](https://github.com/ciscospark/spark-js-sdk/tree/master/packages/node_modules/%40ciscospark/spark-core) consumes it [here](https://github.com/ciscospark/spark-js-sdk/blob/master/packages/node_modules/%40ciscospark/spark-core/src/spark-core.js#L344-L347). The problem is there's no way (right now) to pass extra config to it and, more unfortunately, `spark.request` is a `setOnce` property, so it can't be replaced at at run time.

I'd really like to get better support for proxies in place; the best way to help get it prioritized is to request the feature through [developer support](https://developer.ciscospark.com/support.html).

**Comment by gowrikvk** [comment]
Any solution for this problem? Please let me know.

**Comment by mattnorris** [comment]
@gowrikvk unfortunately not. But please [contact developer support](https://developer.webex.com/support.html) to help us prioritize it.
